### ISSUE TITLE
surface

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/pyoracc#12]
@surface is a valid structure marker

**Comment by jayanthkmr** [comment]
Yeah that structure marker "surface" is already there.

The issue is that annotator used "Suface" instead of surface.

P459150 | line 4 | 'suface' | #N/A | Info: Failed with message: Illegal @STRING 'suface' (line 4) in output/P459150.atf | ATF Issue
-- | -- | -- | -- | -- | --
P459157 | line 4 | 'suface' | #N/A | Info: Failed with message: Illegal @STRING 'suface' (line 4) in output/P459157.atf | ATF Issue
P459165 | line 4 | 'suface' | #N/A | Info: Failed with message: Illegal @STRING 'suface' (line 4) in output/P459165.atf | ATF Issue
P459149 | line 4 | 'suface' | #N/A | Info: Failed with message: Illegal @STRING 'suface' (line 4) in output/P459149.atf | ATF Issue
P365469 | line 4 | 'suface' | #N/A | Info: Failed with message: Illegal @STRING 'suface' (line 4) in output/P365469.atf | ATF Issue

https://cdli.ucla.edu/search/search_results.php?SearchMode=Text&ObjectID=P459150

**Comment by epageperron** [comment]
Thanks ! corrected.
